### PR TITLE
Fix #377 - undefined variables

### LINKED ISSUE #377: Notice PHP : Variable is undefined
Hello,
In the file \CAS\Client.php (phpCAS version 1.3.8) there are undefined variable(s) :

Line 1438 : Variable $text_response is undefined.
Line 1438 : Variable $tree_response is undefined.
Line 1454 : Variable $text_response is undefined.
Line 1454 : Variable $tree_response is undefined.
Line 1461 : Variable $text_response is undefined.
Line 1461 : Variable $tree_response is undefined.
Line 1483 : Variable $text_response is undefined.
Line 1483 : Variable $tree_response is undefined.
Line 2004 : Variable $headers is undefined.
Line 2004 : Variable $err_msg is undefined.
Line 2006 : Variable $err_msg is undefined.
Line 2080 : Variable $headers is undefined.
Line 2080 : Variable $err_msg is undefined.
Line 2082 : Variable $err_msg is undefined.
Line 2724 : Variable $headers is undefined.
Line 2724 : Variable $cas_response is undefined.
Line 2741 : Variable $cas_response is undefined.
Line 2805 : Variable $cas_response is undefined.
Line 2992 : Variable $err_code is undefined.
Line 2992 : Variable $err_msg is undefined.
Line 2994 : Variable $err_msg is undefined.
Line 2994 : Variable $err_code is undefined.
Line 3237 : Variable $headers is undefined.
Line 3237 : Variable $err_msg is undefined.
Line 3239 : Variable $err_msg is undefined.

Greetings

### PR DESCRIPTION
**Pull request by DeyV**

### CODE REVIEW

**Comment by jfritschi** [comment]
Thanks @DeyV 

Can you please check why some of the integration tests fail?

**Comment by jfritschi** [comment]
Some of the tests are still failing :-(

**Comment by DeyV** [comment]
Its hard to fix because this error is not connected with my fix

Can you run retest on previous commit?
(It's look like composer or cache problem on php 7.1 version)

**Comment by jfritschi** [comment]
Looking at the logs:
- PHP 7.1 fails due to: _phpstan/phpstan 1.5.4 requires php ^7.2|^8.0 -> your PHP version (7.1.33) does not satisfy that requirement_
- You introduced PHP 8.1 into the composer testing cycle and something "fails".. Not exactly sure what the issue is...

**Comment by DeyV** [comment]
At this moment this test don't work on my fork
So after previous problem it was my try to fix both - 7.1 problem 
(that looks different)
And missing 8.1

**Comment by jfritschi** [comment]
Well there is always the question...  The issue is that older php versions are often part of the base Linux operating system (e.g. Enterprise Linux) and therefor remain supported even longer than announced by php.net

We had the discussion already last in #380 year if we should drop 7.1. and 7.2 to allow for newer phpunit...

**Comment by jfritschi** [comment]
Please just remove php 7.1. from testing and also remove the composer workarounds your added to make 7.1 work.

A wild guess is that this may create the issues on php 8.1. If this does not work we can then also add the flag:  "experimental: true" to the test.yml in the 8.1 definition. 
Then we can figure out over time what the issue is with the actions under 8.1 ... Some strange permission error that i tried tracking down but all my attempts to fix it failed so far.

**Comment by jfritschi** [comment]
Thanks for your contribution... 

The php 8.1 issues went away after merging. Seems to be some weird permission issue when it's a pull request :-(

**Pull request merged**
