### PR TITLE
Disabling error printing

### LINKED ISSUE #392: No ability to disable displaying errors directly into the response.
Right now, there are places in the library where error messages are displayed directly into the response, mainly:

1. [AuthenticationException](https://github.com/apereo/phpCAS/blob/master/source/CAS/AuthenticationException.php). Lines 74-75:
```php
$client->printHTMLHeader($lang->getAuthenticationFailed());
printf(
    $lang->getYouWereNotAuthenticated(),
    htmlentities($client->getURL()),
    isset($_SERVER['SERVER_ADMIN']) ? $_SERVER['SERVER_ADMIN']:''
);
```

2. [CAS.php](https://github.com/apereo/phpCAS/blob/master/source/CAS.php). Lines 598-602:
```php
if (self::$_PHPCAS_VERBOSE) {
    echo "<br />\n<b>phpCAS error</b>: <font color=\"FF0000\"><b>" . __CLASS__ . "::" . $function . '(): ' . htmlentities($msg) . "</b></font> in <b>" . $file . "</b> on line <b>" . $line . "</b><br />\n";
} else {
    echo "<br />\n<b>Error</b>: <font color=\"FF0000\"><b>". DEFAULT_ERROR ."</b><br />\n";
}
```

Right now the only way to disable this is to make workarounds using buffering or modifying library using composer-patches.
Users may want to handle errors in their own fashion, and displaying messages directly is not a good way to do it.

As a partial solution for first case it could be do like so:
```php
$messages[] = sprintf(
    $lang->getYouWereNotAuthenticated(),
    htmlentities($client->getURL()),
    isset($_SERVER['SERVER_ADMIN']) ? $_SERVER['SERVER_ADMIN']:''
);
```

but it does not solve `$client->printHTMLHeader($lang->getAuthenticationFailed());` line and second case.
In my opinion phpCAS should offer some way (preferably config option) to disable writing error messages directly to the response.

### PR DESCRIPTION
**Pull request by Magiczne**
Closes #392

### CODE REVIEW

**Comment by jfritschi** [comment]
Thanks for the pull.

Shouldn't we just extend the exiting $_PHPCAS_VERBOSE to also cover the exception case? Seems like it's more or less the same topic the same and I don't see much benefit of complicating things more....

Any other opinions? @phy25 ?

**Comment by Magiczne** [comment]
@jfritschi Sure i thought about that, but it would mean that this one line of HTML will be removed:
```php
echo "<br />\n<b>Error</b>: <font color=\"FF0000\"><b>". DEFAULT_ERROR ."</b><br />\n";
```

But I think since it only shows default error it could be removed and that would mean using `$_PHPCAS_VERBOSE` will show the HTML.

**Comment by Magiczne** [comment]
I've updated PR with approach based on existing verbosity flag.

**Comment by jfritschi** [comment]
Closes #129

**Comment by jfritschi** [comment]
Thanks for your contribution!

**Comment by Magiczne** [comment]
@jfritschi No problem. When the new version release can be expected?

**Comment by jfritschi** [comment]
No, release is planned in the near future and I wont have the time until September... We are lacking real active maintainers at the moment.

**Comment by lewart** [comment]
I thing this change was pretty awaited by the authors of many applications and will be used as soon as it's released.
Thanks goes to You, Magiczne!

I think that after a commit 77fa7453 above, the constant DEFAULT_ERROR is no longer used. Can it be removed?

**Comment by jfritschi** [comment]
@lewart The constant has been removed... Thank you @Magiczne for the PR

**Pull request merged**
