### PR TITLE
#316 improve attribute handling

### LINKED ISSUE #316: attribute parsing mangles name and value in jasig-style attributes
Our CAS server submits the attributes in a slightly different layout to the styles parsed in the phpCAS client. As the client does no complete XML parsing it merges the attribute name and value. 

the Server response in our case is:

```
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
  <cas:authenticationSuccess>
    <cas:user>jsmith</cas:user>
    <cas:attributes>
      <cas:attribute>
        <cas:name>surname</cas:name>
        <cas:value>Smith</cas:value>
      </cas:attribute>
      <cas:attribute>
        <cas:name>givenName</cas:name>
        <cas:value>John</cas:value>
      </cas:attribute>
      <cas:attribute>
        <cas:name>memberOf</cas:name>
        <cas:value>['CN=Staff,OU=Groups,DC=example,DC=edu', 'CN=Spanish Department,OU=Departments,OU=Groups,DC=example,DC=edu']</cas:value>
      </cas:attribute>
    </cas:attributes>
    <cas:proxyGrantingTicket>PGTIOU-84678-8a9d2sfa23casd</cas:proxyGrantingTicket>
  </cas:authenticationSuccess>
</cas:serviceResponse>
```

the output of the standard parsing using `print_r()` is:

```
Array
(
    [attribute] => Array
        (
            [0] => surnameSmith
            [1] => givenNameJohn
            [2] => memberOf['CN=Staff,OU=Groups,DC=example,DC=edu', 'CN=Spanish Department,OU=Departments,OU=Groups,DC=example,DC=edu']
        )
)
```

### PR DESCRIPTION
**Pull request by ts23**
This pull request  introduces a slightly deeper XML parsing. It recursively goes through the DOM and moves the elements into array hierarchies. A second step flattens the Array before the relevant attributes are returned. Sub-elements are combined and JSON style Arrays are split.

Unfortunately there are whitespace changes in the file as well as I was trying to create a consistent sytle in the file

This fixes #316.

### CODE REVIEW

**Comment by phy25** [comment]
Haven't read the code in depth, but it looks like a lot of functions are added including _startsWith, _endsWith, _flatten_array, _parse_json_like_array_value, _xml_to_array.

Actual range that has been modified in regards to attribute handling: https://github.com/apereo/phpCAS/pull/317/files#diff-a00200a72a938f71b0d575996889cc43R3341-R3666

**Comment by jfritschi** [comment]
Looks okay to me ... Any further comments from @phy25 ?

**Comment by phy25** [comment]
@jfritschi I just feel like some utility functions like `_startsWith` and `_endsWith` can be avoided (from a "no so many utility functions perspective"), but I haven't quite read the code so I am not sure.

The added feature definitely looks nice, but I would like to read the parsing code more closely later - since it's parsing more XML than before.

**Comment by jfritschi** [comment]
No rush. Just finish your review and let us know your thoughts.

**Comment by ts23** [comment]
yes _startsWith and _endsWith could be inlined ... but whats the difference except code duplication ... however I have no preferences

**Comment by ts23** [comment]
I had a look at the unit tests, but wasn't successful running them. Do I need a connection to the CAS server to run them ? 
Should the testing not go in  
[test/CAS/Tests/Cas20AttributesTest.php](https://github.com/apereo/phpCAS/blob/master/test/CAS/Tests/Cas20AttributesTest.php) ?

**Comment by phy25** [comment]
@ts23 To run tests locally for now you need PHPUnit 3 (I have a patch to make it run for PHPUnit <8 at #320). I don't think you need an actual CAS server to run the tests because the test itself will simulate one.

And yes, https://github.com/apereo/phpCAS/blob/master/test/CAS/Tests/Cas20AttributesTest.php should be the right place to add tests.

**Comment by ts23** [comment]
I've updated my master and tried to run the tests but they did not run through:
```
phpunit TestSuite.php
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.

R..................................................R....
```
<html><head><title>CAS Authentication failed!</title></head><body><h1>CAS Authentication failed!</h1><p>You were not authenticated.</p><p>You may submit your request again by clicking <a href="http://www.service.com/">here</a>.</p><p>If the problem persists, you may contact <a href="mailto:root@localhost">the administrator of this site</a>.</p></body></html>.<html><head><title>CAS Authentication failed!</title></head><body><h1>CAS Authentication failed!</h1><p>You were not authenticated.</p><p>You may submit your request again by clicking <a href="http://www.service.com/">here</a>.</p><p>If the problem persists, you may contact <a href="mailto:root@localhost">the administrator of this site</a>.</p></body></html>.<html><head><title>CAS Authentication failed!</title></head><body><h1>CAS Authentication failed!</h1><p>You were not authenticated.</p><p>You may submit your request again by clicking <a href="http://www.service.com/">here</a>.</p><p>If the problem persists, you may contact <a href="mailto:root@localhost">the administrator of this site</a>.</p></body></html>..<html><head><title>CAS Authentication failed!</title></head><body><h1>CAS Authentication failed!</h1><p>You were not authenticated.</p><p>You may submit your request again by clicking <a href="http://www.service.com/">here</a>.</p><p>If the problem persists, you may contact <a href="mailto:root@localhost">the administrator of this site</a>.</p></body></html>.<html><head><title>CAS Authentication failed!</title></head><body><h1>CAS Authentication failed!</h1><p>You were not authenticated.</p><p>You may submit your request again by clicking <a href="http://www.service.com/">here</a>.</p><p>If the problem persists, you may contact <a href="mailto:root@localhost">the administrator of this site</a>.</p></body></html>

```
.I.I 65 / 79 ( 82%)
I.I.R.........                                                    79 / 79 (100%)


Time: 3.12 seconds, Memory: 6.00MB

There were 3 risky tests:

1) CAS_Tests_AuthenticationTest::testRedirect
This test did not perform any assertions

2) CAS_Tests_ProxyTicketValidationTest::testInvalidTicketFailure
Test code or tested code did not (only) close its own output buffers

3) CAS_Tests_ServiceTicketValidationTest::testInvalidTicketFailure
Test code or tested code did not (only) close its own output buffers

OK, but incomplete, skipped, or risky tests!
Tests: 79, Assertions: 412, Incomplete: 4, Risky: 3.
```

Any hints?

**Comment by jfritschi** [comment]
@phy25 Can this be merged?

**Comment by ts23** [comment]
> @phy25 Can this be merged?

**Comment by ts23** [comment]
This close was a mistake

**Comment by phy25** [comment]
@jfritschi Generally I didn't see an issue (it's a lot of code involved indeed). Currently it's kind of a pending unittest stage. I don't mind if you want to merge this first; I can try working on tests later.

**Pull request merged**
